fail_on_severity: 'low'
allow_licenses:
  - 'BSD-2-Clause'
  - 'BSD-3-Clause'
  - 'BSD-3-Clause-Clear'
  - 'MIT'
  - 'Apache-2.0'
  - 'ISC'
  - 'BlueOak-1.0.0'
  - '0BSD'
  - 'Python-2.0'
  - 'Zlib'
  - 'MPL-2.0'
  - 'MIT-CMU'
fail-on-scopes:
  - 'runtime'
license-check: true
vulnerability-check: true
allow-dependencies-licenses:
  - 'pkg:pypi/matplotlib@3'
  - 'pkg:pypi/pillow@11.2.1'
  - 'pkg:pypi/protobuf@6.30.2'
  - 'pkg:pypi/pytz@2025.2'
  - 'pkg:pypi/regex@2024.11.6'
  - 'pkg:pypi/filelock@3.18.0'
  - 'pkg:pypi/setuptools@80.3.1'
  - 'pkg:pypi/packaging@25.0'
  - 'pkg:pypi/python-dateutil@2.9.0'