CI:
- any:
  - changed-files:
    - any-glob-to-any-file: ['.github/**/*', 'Jenkinsfile']

tokenizers_cpp:
- any:
  - changed-files:
    - any-glob-to-any-file: 'src/**/*'

tokenizers_py:
- any:
  - changed-files:
    - any-glob-to-any-file: 'python/**/*'

tokenizers_test:
- any:
  - changed-files:
    - any-glob-to-any-file: 'tests/**/*'

build:
- any:
  - changed-files:
    - any-glob-to-any-file: ['**/CMakeLists.txt', '**/*.toml', '**/*.cmake']

dependencies:
- all:
  - changed-files:
    - any-glob-to-any-file: '**/requirement*.txt'
    - all-globs-to-all-files: '!**/CMakeLists.txt'
