# this property will be overwritten with value generated by cmake configure step

from pathlib import Path

__version__ = "0.0.0.0"

def read_version_from_file():
    root = Path(__file__).resolve().parent.parent.parent
    version_file = root / "__version__"

    if version_file.exists():
        version = version_file.read_text(encoding="utf-8").strip()
        return version

    raise FileNotFoundError(f"__version__ file not found ({version_file})")

try:
    __version__ = read_version_from_file()
    print(f"Version: {__version__}")
except Exception as e:
    print(f"Error: {e}")
    __version__ = "0.0.0.0"